### PR TITLE
Brought back the thumper

### PR DESCRIPTION
**Pull request by Mailaender**
as it now really spawns sandworms. Merged medic and engineer into a new support infantry class.

### CODE REVIEW

**Comment by penev92** [comment]
So... Medic, Engineer and Thumper infantry into one?

**Comment by Mailaender** [comment]
The diff is almost impossible to read. It is just

MEDIC + ENGINEER = SUPPORT
MEDIC -> THUMPER

Medics never existed in Dune 2000. They were introduced to do something with the unused sprites as worms did not exist in the mod.

**Comment by Mailaender** [comment]
You can get rid of the merge commit in your branch by rebasing against bleed. It will then automatically vanish.

**Comment by penev92** [comment]
Any idea about the Travis crash?

**Comment by Mailaender** [comment]
Ah damn. That is my fault. I forgot to replace ENGINEER with SUPPORT in https://github.com/penev92/OpenRA/blob/bleed_sandworm/mods/d2k/rules/structures.yaml#L642.

**Comment by Micr0Bit** [comment]
no way to chancel the thumper ... (and yes , it was possible to deactivate the "thumping" in the original)
also there is no little sand-cloud coming up when the thumper hits the ground ... and there is no sound that indicates the thumper ... and the sound is quite important here ... 

https://www.youtube.com/watch?v=ul2Wc5uTrsY

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/OpenRA/pull/7130.

**Pull request merged**
